package com.scribsync.scribsync.data

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Environment
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Locale

object PdfExporter {

    fun export(context: Context, meeting: Meeting): File? {
        return try {
            val document = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
            val page = document.startPage(pageInfo)
            drawContent(page.canvas, meeting)
            document.finishPage(page)

            val dir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
                ?: context.filesDir
            val safeName = meeting.title.replace(Regex("[^A-Za-z0-9 _-]"), "").trim().replace(" ", "_")
            val file = File(dir, "${safeName}_transcript.pdf")
            document.writeTo(FileOutputStream(file))
            document.close()
            file
        } catch (e: Exception) {
            null
        }
    }

    private fun drawContent(canvas: Canvas, meeting: Meeting) {
        val pageWidth = 595f
        val margin = 48f
        val contentWidth = pageWidth - 2 * margin
        val dateFormat = SimpleDateFormat("MMMM d, yyyy 'at' h:mm a", Locale.getDefault())

        val titlePaint = Paint().apply {
            color = Color.parseColor("#1A5EBF")
            textSize = 20f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val metaPaint = Paint().apply {
            color = Color.parseColor("#777777")
            textSize = 11f
            isAntiAlias = true
        }
        val dividerPaint = Paint().apply {
            color = Color.parseColor("#DDDDDD")
            strokeWidth = 1f
        }
        val speakerPaint = Paint().apply {
            textSize = 10f
            isFakeBoldText = true
            isAntiAlias = true
            letterSpacing = 0.08f
        }
        val bodyPaint = Paint().apply {
            color = Color.parseColor("#222222")
            textSize = 11f
            isAntiAlias = true
        }
        val footerPaint = Paint().apply {
            color = Color.parseColor("#AAAAAA")
            textSize = 9f
            isAntiAlias = true
        }

        var y = 56f

        canvas.drawText(meeting.title, margin, y, titlePaint)
        y += 20f

        val speakers = meeting.transcriptEntries.map { it.speakerLabel }.distinct().size
        canvas.drawText(
            "${dateFormat.format(meeting.date)}  ·  ${formatDuration(meeting.durationSeconds)}  ·  $speakers speaker${if (speakers != 1) "s" else ""}",
            margin, y, metaPaint
        )
        y += 14f

        canvas.drawLine(margin, y, pageWidth - margin, y, dividerPaint)
        y += 18f

        val speakerColorList = listOf(
            Color.parseColor("#1A5EBF"),
            Color.parseColor("#00796B"),
            Color.parseColor("#4C5CBC"),
            Color.parseColor("#7B1FA2")
        )
        val speakerColorMap = mutableMapOf<String, Int>()
        var colorIdx = 0

        for (entry in meeting.transcriptEntries) {
            if (y > 800f) break

            val color = speakerColorMap.getOrPut(entry.speakerLabel) {
                speakerColorList[colorIdx++ % speakerColorList.size]
            }
            speakerPaint.color = color
            canvas.drawText(entry.speakerLabel.uppercase(), margin, y, speakerPaint)
            y += 14f

            val words = entry.text.split(" ")
            var line = ""
            for (word in words) {
                val candidate = if (line.isEmpty()) word else "$line $word"
                if (bodyPaint.measureText(candidate) > contentWidth) {
                    canvas.drawText(line, margin, y, bodyPaint)
                    y += 14f
                    line = word
                    if (y > 800f) break
                } else {
                    line = candidate
                }
            }
            if (line.isNotEmpty() && y <= 800f) {
                canvas.drawText(line, margin, y, bodyPaint)
                y += 14f
            }
            y += 6f
        }

        canvas.drawText("Generated by ScribeSync", margin, 826f, footerPaint)
    }

    private fun formatDuration(seconds: Int): String {
        val h = seconds / 3600
        val m = (seconds % 3600) / 60
        val s = seconds % 60
        return if (h > 0) "%dh %02dm %02ds".format(h, m, s) else "%dm %02ds".format(m, s)
    }
}
